workflows:
  flutter-build:
    name: Build Flutter app
    # Указываем платформу, для которой выполняем сборку
    platform: flutter
    
    # Указываем, что нужно сделать с Android и iOS
    android:
      # Используем команду Flutter для сборки Android
      flutter:
        channel: stable
        build: apk --release
        
    ios:
      # Используем команду Flutter для сборки iOS
      flutter:
        channel: stable
        build: ios --release --no-codesign
        
    # Перед сборкой установить зависимости
    pre_build:
      - flutter pub get
    
    # После сборки выполнить дополнительные шаги
    post_build:
      - echo "Build finished!"
    
    # Артефакты (что нужно сохранить после сборки)
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
